name: Skills Extraction

on:
  push:
    branches:
      - main

jobs:
  extract-skills:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Run skill extractor
#        env:
#          DRIVE_KEY: ${{ secrets.DRIVE_KEY }}
#          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
#        run: python skills.py

      - name: Run skill level extractor
        env:
          DRIVE_KEY: ${{ secrets.DRIVE_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python level.py

      - name: Run job level extractor
        env:
          DRIVE_KEY: ${{ secrets.DRIVE_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python job_level.py