name: Skills & Levels Extraction

on:
  push:
    branches:
      - main

jobs:
#  extract-skills:
#    runs-on: ubuntu-latest
#    env:
#      DRIVE_KEY: ${{ secrets.DRIVE_KEY }}
#      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.x'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Run skill extractor
#        run: python skills.py

  extract-skill-level:
    runs-on: ubuntu-latest
    env:
      DRIVE_KEY: ${{ secrets.DRIVE_KEY }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run skill level extractor
        run: python level.py

  extract-job-level:
    runs-on: ubuntu-latest
    env:
      DRIVE_KEY: ${{ secrets.DRIVE_KEY }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job level extractor
        run: python job_level.py
